#!/bin/bash
# init-firewall.sh — runs in the privileged init container.
#
# Reads a flat input file (/etc/ralph/firewall-input.txt) pre-extracted by the
# launcher from `ralph.config.yaml`. Applies a default-deny iptables policy
# with a narrow allowlist; writes the resulting state to
# /etc/ralph/iptables-state.txt (consumed by `bin/ralph audit`); self-verifies
# and aborts on misconfiguration.
#
# The flat input file shape:
#   DNS_RESOLVER=<ip>
#   DB_PORT=<port or empty>
#   DOMAIN <fqdn>
#   DOMAIN <fqdn>
#   ...
#
# Sharing the netns with the workload container means the workload inherits this
# policy but has no NET_ADMIN to modify it.

set -euo pipefail
IFS=$'\n\t'

INPUT=/etc/ralph/firewall-input.txt
STATE=/etc/ralph/iptables-state.txt

[ -f "$INPUT" ] || { echo "[firewall] no input at $INPUT" >&2; exit 1; }

ALLOWED_DOMAINS=()
DNS_RESOLVER="1.1.1.1"
DB_PORT=""

while IFS= read -r line; do
  case "$line" in
    DNS_RESOLVER=*) DNS_RESOLVER="${line#DNS_RESOLVER=}" ;;
    DB_PORT=*)      DB_PORT="${line#DB_PORT=}" ;;
    DOMAIN\ *)      ALLOWED_DOMAINS+=("${line#DOMAIN }") ;;
    "" | \#*)       ;;
  esac
done < "$INPUT"

# Always include api.anthropic.com.
have_anthropic=0
for d in "${ALLOWED_DOMAINS[@]:-}"; do
  [ "$d" = "api.anthropic.com" ] && have_anthropic=1
done
[ "$have_anthropic" -eq 0 ] && ALLOWED_DOMAINS+=("api.anthropic.com")

echo "[firewall] dns_resolver=$DNS_RESOLVER db_port=${DB_PORT:-none} domains=${#ALLOWED_DOMAINS[@]}"

# ---- iptables: flush and rebuild ----
# Preserve Docker's internal DNS NAT rules.
DOCKER_DNS_RULES=$(iptables-save -t nat | grep "127\.0\.0\.11" || true)

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
ipset destroy allowed-domains 2>/dev/null || true

if [ -n "$DOCKER_DNS_RULES" ]; then
  iptables -t nat -N DOCKER_OUTPUT 2>/dev/null || true
  iptables -t nat -N DOCKER_POSTROUTING 2>/dev/null || true
  echo "$DOCKER_DNS_RULES" | xargs -L 1 iptables -t nat
fi

# Loopback always allowed.
iptables -A INPUT  -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# DNS only to the configured resolver, UDP/53.
iptables -A OUTPUT -p udp --dport 53 -d "$DNS_RESOLVER" -j ACCEPT
iptables -A INPUT  -p udp --sport 53 -s "$DNS_RESOLVER" -j ACCEPT

# No outbound TCP/22 (SSH). No broad UDP. No outbound TCP except to allowed_domains.

ipset create allowed-domains hash:net

for domain in "${ALLOWED_DOMAINS[@]}"; do
  [ -z "$domain" ] && continue
  echo "[firewall] resolving $domain"
  ips=$(dig +noall +answer +short A "$domain" "@$DNS_RESOLVER" 2>/dev/null || true)
  if [ -z "$ips" ]; then
    echo "[firewall] WARNING: failed to resolve $domain" >&2
    continue
  fi
  while IFS= read -r ip; do
    [[ "$ip" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]] || continue
    ipset add -exist allowed-domains "$ip"
  done <<<"$ips"
done

# Optional: allow host_ip:db_port for sidecar databases.
if [ -n "$DB_PORT" ] && [ "$DB_PORT" != "null" ]; then
  HOST_IP=$(ip route | awk '/default/ {print $3; exit}' || true)
  if [ -n "$HOST_IP" ]; then
    iptables -A OUTPUT -p tcp -d "$HOST_IP" --dport "$DB_PORT" -j ACCEPT
    iptables -A INPUT  -p tcp -s "$HOST_IP" --sport "$DB_PORT" -m state --state ESTABLISHED -j ACCEPT
  fi
fi

iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

iptables -A INPUT  -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A OUTPUT -m set --match-set allowed-domains dst -j ACCEPT
iptables -A OUTPUT -j REJECT --reject-with icmp-admin-prohibited

# ---- Write the state file for `bin/ralph audit` to consume ----
{
  echo "# Generated by init-firewall.sh at $(date -u +%FT%TZ)"
  echo "# dns_resolver=$DNS_RESOLVER"
  echo "# db_port=${DB_PORT:-none}"
  echo
  echo "## allowed_domains:"
  for d in "${ALLOWED_DOMAINS[@]}"; do echo "$d"; done
  echo
  echo "## ipset allowed-domains:"
  ipset list allowed-domains
  echo
  echo "## iptables-save:"
  iptables-save
} > "$STATE"

# ---- Self-verify ----
if curl --connect-timeout 5 -o /dev/null -s -w "%{http_code}" https://example.com 2>&1 | grep -q -E '^[12]'; then
  echo "[firewall] ERROR: example.com reachable — firewall not enforcing" >&2
  exit 1
fi
if ! curl --connect-timeout 5 -o /dev/null -s -w "%{http_code}" https://api.anthropic.com 2>&1 | grep -q -E '^[123]'; then
  echo "[firewall] ERROR: api.anthropic.com unreachable — firewall over-restrictive" >&2
  exit 1
fi

echo "[firewall] configured: ${#ALLOWED_DOMAINS[@]} domains allowed; state at $STATE"
